services:
  postgres:
    build:
      context: ./postgres
      dockerfile: dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
    networks:
      - testnet
    volumes:
      - db-data:/var/lib/postgresql/data:delegated

volumes:
  db-data:

networks:
  testnet:
    driver: bridge